---
- name: Install microservices
  hosts: ipt_poc_rhel9
  become: yes

  tasks:
    - name: Update packages
      dnf:
        name: '*'
        state: latest
    
    - name: Subscription Manager
      command: |
        subscription-manager config --rhsm.manage_repos=1
        subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms

    - name: Install EPEL
      dnf:
        name: epel-release
        state: present

    - name: Install podman
      dnf:
        name: podman
        state: present

    - name: Install git
      dnf:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: https://github.com/AlexDias95/ipt-projecto-integrado2-2024.git
        dest: /ipt-projecto-integrado2-2024

    - name: Start podman service
      service:
        name: podman
        state: started
        enabled: yes

    - name: Copy the .env file
      copy:
        src: ../docker/.env
        dest: /ipt-projecto-integrado2-2024/code/docker/.env

    - name: Load environment variables
      shell: source /ipt-projecto-integrado2-2024/code/docker/.env

    - name: Build the podman-compose
      command: podman compose up -d
      args:
        chdir: /ipt-projecto-integrado2-2024/code/docker